--- drivers/media/platform/msm/camera_v2/sensor/flash/Makefile
+++ drivers/media/platform/msm/camera_v2/sensor/flash/Makefile
@@ -3,8 +3,3 @@ ccflags-y += -Idrivers/media/platform/msm/camera_v2
 ccflags-y += -Idrivers/media/platform/msm/camera_v2/common
 ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
 obj-$(CONFIG_MSMB_CAMERA) += msm_flash.o
-obj-$(CONFIG_MSMB_CAMERA) += msm_led_flash.o
-obj-$(CONFIG_MSMB_CAMERA) += msm_led_trigger.o
-obj-$(CONFIG_MSMB_CAMERA) += msm_led_i2c_trigger.o
-obj-$(CONFIG_MSMB_CAMERA) += adp1660.o
-obj-$(CONFIG_MSMB_CAMERA) += msm_led_torch.o